server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/film_comment_system?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mvc:
    static-path-pattern: /files/**
  web:
    resources:
      static-locations: file:G:/电影评论系统/带敲/film_comment_system/files/,classpath:/static/

# 配置 MyBatis 实体和 XML 映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 文件上传的前缀 URL
fileBaseUrl: http://localhost:9090


# Configure Baidu NLP
baidu:
  nlp:
    api-key: w24TF3V9eSBYvW90eaPiSC3U
    secret-key: NREt34wJcTSccXtBTZl4bBekr1MOPZCw